openapi: 3.1.0
info:
  title: Data Consumer Adapter
  version: 0.1.0
paths:
  /api/v1/conversations:
    post:
      tags:
        - conversations
      summary: >
        Initiierung eines Nachweisabrufs einen oder mehrere Nachweise durch
        einen Data Consumer (DC). Anlage einer "conversation" mit Information
        über alle abzurufende Nachweise und Information über den
        Antragsstellenden (Bürger und Unternehmen).
      description: >
        Dieser endpoint wird verwendet für den Data Consumer (DC) bei einem
        Nachweisabruf mit Hilfe des lokal in der Nähe des Data Consumer
        installierten Data Consumer Adapters. Es wird die Backendkomponente des
        DC angesprochen. Die Komponente ist somit vom unsicheren Internet
        geschützt.
      operationId: startConversation
      requestBody:
        description: >
          Initiierung eines Nachweisabrufs einer oder mehrere Nachweise durch
          einen Data Consumer (DC). Die redirectUrl wird verwendet, damit im
          Rahmen eines redirects über den Browswer des Antragsstellenden der
          Data Consumer Adapter angesprochen werden kann. Als Antwort erhält der
          Data Consumer ein ConversationID auf deren Grundlage er zu einem
          späteren Zeitpunkt die Nachweise abrufen kann.
        content:
          application/json:
            schema:
              type: object
              required:
                - componentId
                - identifierPersonList
                - language
                - redirectUrl
                - requestedEvidencesList
              properties:
                componentId:
                  type: string
                  format: UUID
                  description: >
                    Mittels componentID kann der DCA anschließend eine Abfrage an IAM
                    für Behörden (IAMfB) stellen und dabei sowohl die
                    fachverantwortliche Stelle als auch die
                    betriebsverwantwortliche Stelle des Data Consumers
                    ermitteln.
                identifierPersonList:
                  type: array
                  minItems: 1
                  maxItems: 2
                  items:
                    $ref: "#/components/schemas/IdentifierPerson"
                  description: >
                    Es dürfen maximal zwei Einträge enthalten sein – jeweils ein
                    Eintrag für natürliche und juristische Personen.
                language:
                  type: string
                  description: Präferierte Sprache der zu liefernden Nachweisen
                  example: de
                redirectUrl:
                  type: string
                  format: url
                requestedEvidencesList:
                  type: array
                  items:
                    $ref: "#/components/schemas/ConversationStart.RequestedEvidence"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversationId:
                    type: string
                    format: uuid
                    description: Eindeutige ID der gestarteten Konversation. Die ID wird später
                      verwendet, um die mit dieser Methode eingereichten
                      Informationen bei späteren Nachweisabrufen abzuholen.
                    example: 123e4567-e89b-12d3-a456-426614174000
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
  "/api/v1/conversations/{conversationId}/evidencetypes":
    get:
      tags:
        - conversations
      summary: Die abzurufenden Nachweistypen und die Beschreibung der Nachweistypen
        werden zu einer conversationId gespeichert.
      description: Dieser end point kann direkt von einem Browser (über Internet)
        abgerufen werden.
      operationId: getEvidenceTypesForConversation
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                items:
                  type: object
                  properties:
                    evidenceTypeId:
                      type: string
                      format: uuid
                      description: Identifier des Nachweistyps
                      example: 9151f21f-43ae-43b4-92f3-f4af67cdf544
                    evidenceTypeName:
                      type: string
                      description: Name des Nachweistyps entsprechend Information in RDN (Registerdatennavigation)
                      example: Geburtsurkunde
                    evidenceProviderName:
                      type: string
                      description: Name der datenliefernden Stelle entsprechend Information in RDN (Registerdatennavigation)
                      example: Standesamt Hamburg
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
  "/api/v1/conversations/{conversationId}/preview-data":
    get:
      tags:
        - conversation
      summary: Liefert Nachweisdaten inkl. Vorlage für ein rendering der Nachweisdaten
        in einem menschenlesbaren Format.
      operationId: getPreviewData
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: evidenceTypeIds
          in: query
          required: false
          schema:
            type: string
            format: uuid
          description: optionale Auswahl der Nachweistypen sofern nicht alle Nachweistypen geliefert werden sollen
      responses:
        "200":
          description: Die Preview-Daten wurden erfolgreich geholt.
          content:
            application/json:
              schema:
                type: object
                properties:
                  previewData:
                    type: array
                    items:
                      type: object
                      properties:
                        evidenceTypeId:
                          type: string
                          format: uuid
                        structuredData:
                          type: object
                          description: Structured Data for the Evidence Type
                        renderingTemplate:
                          type: object
                          properties:
                            type:
                              type: string
                              enum:
                                - XSLT
                                - JSON
                          description: Format für das Rendering der Nachweidaten in einem menschenlesbaren Format
                        content:
                          type: string
                          description: Inhalt der Vorlage für das Rendering der Nachweisdaten in einem menschenlesbaren Format
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - bearerAuth: []
  "/api/v1/conversations/{conversationId}/consent":
    patch:
      summary: Zustimmung des Antragsstellenden zur Verwendung von Nachweistypen
        innerhalb einer bestehenden Konversation speichern, siehe §5 EGovG.
      operationId: patchConsent
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Die ID der bestehenden Konversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - evidenceConsents
              properties:
                evidenceConsents:
                  type: array
                  items:
                    type: object
                    properties:
                      evidenceTypeId:
                        type: string
                        format: uuid
                        description: UUID des Nachweistyps
                      consentGiven:
                        type: boolean
                        description: Zustimmung des Nutzers zur Verwendung dieses Nachweises
                  minItems: 1
      responses:
        "204":
          description: Zustimmung erfolgreich gespeichert
        "400":
          description: Ungültige Anfrage (z. B. Bezugnahme zu einem evidenceTypeId, der
            nicht abgefragt werden sollte)
        "404":
          description: Konversation nicht gefunden
      security:
        - bearerAuth: []
  "/api/v1/conversations/{conversationId}/evidences":
    get:
      summary: >
        Liefert Consent-Status für alle angefragte Nachweistypen und
        Nachweisdaten für Nachweistypen, die der Antragsstellende abrufen
        möchte.
      operationId: getEvidences
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Die ID der bestehenden Konversation
      responses:
        "200":
          description: Liste der Nachweistypen mit Consent-Status und Nachweisdaten,
            sofern der Antragsstellende hierzu ein consent gegeben hat.
          content:
            application/json:
              schema:
                properties:
                  conversationId:
                    type: string
                  evidenceList:
                    type: array
                    items:
                      type: object
                      properties:
                        evidenceTypeId:
                          type: string
                          format: uuid
                        consentGiven:
                          type: [boolean, "null"]
                        evidenceDistribution:
                          type: [object, "null"]
                          properties:
                            fileName:
                              type: string
                            ootsMediaType:
                              $ref: "#/components/schemas/OotsMediaType"
                            evidenceSchema:
                              type: string
                              format: uri
                            downloadUrl:
                              type: string
                              format: uri
        "404":
          description: Konversation nicht gefunden
  "/api/v1/conversations/{conversationId}":
    delete:
      summary: Löscht alle Daten zu einer Konversation
      operationId: deleteConversation
      parameters:
        - name: conversationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Die ID der zu löschenden Konversation
      responses:
        "204":
          description: Konversation erfolgreich gelöscht
        "404":
          description: Konversation nicht gefunden
      security:
        - bearerAuth: []
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        errorMessage:
          type: string
    ConversationStart.RequestedEvidence:
      type: object
      required:
        - requestedEvidenceIdentifier
        - requestedEvidenceOrigin
        - requestedEvidenceTypeDistributionList
      properties:
        requestedEvidenceIdentifier:
          type: string
          format: UUID
          description: Identifikator des Nachweistyps. Dieser kann für nationale Nachweisabrufe im Nachweiskatalog gefunden werden.
          example: 9151f21f-43ae-43b4-92f3-f4af67cdf544
        requestedEvidenceOrigin:
          type: string
          enum:
            - DE
            - EU
            - AT
            - BE
            - BG
            - HR
            - CY
            - CZ
            - DK
            - EE
            - FI
            - FR
            - GR
            - HU
            - IE
            - IT
            - LV
            - LT
            - LU
            - MT
            - NL
            - PL
            - PT
            - RO
            - SK
            - SI
            - ES
            - SE
          description: >
            Herkunft des nachgefragten Nachweistyps entsprechend ISO 3166-1
            Alpha-2 Code in codeliste
            "urn:xoev-de:kosit:codeliste:country-codes". Nur Länder der
            Europäischen Union dürfen eingetragen werden. Wenn der Data Consumer
            Adpater oder die Intermediäre Plattform im Dialog mit dem
            Antragsstellenden nachträglich die Herkunft ermitteln soll und die
            Herkunft nicht Deutschland ist, wird der Wert "EU" eingetragen.
        requestedEvidenceTypeDistributionList:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/RequestedEvidenceTypeDistribution"
        rechtsgrundlage:
          type: string
          description: Hier wird für nationale Abrufe die Rechtsgrundlage für den Nachweisabruf beschrieben
          example: § 9 Handelsgesetzbuch (HGB)
        verarbeitungszweck:
          type: string
          description: >
            Hier wird für nationale Abrufe der Verarbeitungszweck gemäß noch zu
            veröffentlichender Code-Liste eingetragen. Für "Onlinedienst
            (interaktiver) Nachweisabruf ist das "1"
          example: 1
        jurisdictionParameter:
          type: object
          required:
            - zuständigkeitswert
            - zuständigkeitsbestimmung
          properties:
            zuständigkeitswert:
              type: string
              example: "110009000000"
              description: >
                Angabe des Zuständigkeitswerts zur Ermittlung des zuständigen
                Registers. Im Beispiel: Wert des amtlichen Regionalschlüssels
                des  Stadtbezirks Steglitz-Zehlendorf
            zuständigkeitsbestimmung:
                type: string
                example: ars
                description: > 
                  Angabe der (Code Liste) zur Ermittlung des zuständigen Registers.
                  Im Beispiel unten erfolgt die Zuständigkeitsbestimmung nach dem Amtlichen Regionalschlüssel.
    RequestedEvidenceTypeDistribution:
      type: object
      required:
        - ootsMediaTyp
      properties:
        ootsMediaType:
          $ref: "#/components/schemas/OotsMediaType"
        priority:
          type: integer
          minimum: 1
          description: Eindeutige Priorität des Nachweisformats als positive ganze Zahl.
        evidenceSchema:
          type: string
          format: uri
          description: >
            Verweis auf ein Schema in einer definierten Version. Bei
            Nachweisanfragen aus dem EU-Ausland muss der Wert dem Muster
            'https://sr.oots.tech.ec.europa.eu/datamodels/.*' entsprechen.
            example:
            "https://www.xrepository.de/api/xrepository/urn:xoev-de:blk-ag-it-standards:standard:xjustiz_3.6.2:xmlschema"
        transformationSchema:
          type: string
          format: uri
          description: >
            Verweis auf ein Schema, dass ein Subset der geforderten Daten
            definiert. Bei Nachweisanfragen aus dem EU-Ausland muss der Wert dem
            Muster 'https://sr.oots.tech.ec.europa.eu/datamodels/.*'
            entsprechen.
    IdentifierPerson:
      type: object
      required:
        - person
      properties:
        person:
          oneOf:
            - $ref: "#/components/schemas/NaturalPerson"
            - $ref: "#/components/schemas/LegalPerson"
          discriminator:
            propertyName: type
            mapping:
              naturalPerson: "#/components/schemas/NaturalPerson"
              legalPerson: "#/components/schemas/LegalPerson"
              description: Entweder eine natürliche oder eine juristische Person – genau eine muss angegeben werden.
    NaturalPerson:
      type: object
      required:
        - dateOfBirth
        - familyName
        - givenName
        - levelOfAssurance
      properties:
        dateOfBirth:
          type: string
          format: date
        familyName:
          type: string
        givenName:
          type: string
        levelOfAssurance:
          $ref: "#/components/schemas/LevelOfAssurance"
        placeOfBirth:
          type: string
        currentAddress:
          $ref: "#/components/schemas/Address"
        sectorSpecificAttributeList:
          type: array
          items:
            $ref: "#/components/schemas/SectorSpecificAttribute"
        nationality:
          type: string
        townOfBirth:
          type: string
    LegalPerson:
      type: object
      required:
        - legalName
        - levelOfAssurance
        - address
      properties:
        legalName:
          type: string
        levelOfAssurance:
          $ref: "#/components/schemas/LevelOfAssurance"
        registeredAddress:
          $ref: "#/components/schemas/Address"
        legalPersonEIDASIdentifier:
          type: string
          description: eIDAS-konformer Identifier
          example: ES/AT/02635542Y
        legalPersonIdentifier:
          type: string
          description: > 
            Hier erfolgt die Angabe des EUID entsprechend
            Durchführungsverordnung (EU) 2020/2244 der Kommission vom 17.
            Dezember 2020
          example: DE.HRB.123456
        sectorSpecificAttributeList:
          type: array
          items:
            $ref: "#/components/schemas/SectorSpecificAttribute"
    Address:
      type: object
      required:
        - fullAddress
        - thoroughfare
        - locatorDesignator
        - country
        - postCode
        - postCityName
      properties:
        fullAddress:
          type: string
          description: Die vollständige Adresse (Strasse, Postleitzahl, Stadt/Gemeinde, Land)
        thoroughfare:
          type: string
          description: Die Straße ohne Nummer
        locatorDesignator:
          type: string
          description: Die Nummerangabe als Ergänzung zur Straßenangabe
        country:
          type: string
          description: Das Land entsprechend ISO 3166-1 Alpha-2 Code in codeliste "urn:xoev-de:kosit:codeliste:country-codes"
        postCode:
          type: string
          description: Postleitzahl
        postCityName:
          type: string
          description: Stadt oder Gemeinde
    SectorSpecificAttribute:
      type: object
      required:
        - attributeName
        - attributeURI
        - attributeValue
      properties:
        attributeName:
          type: string
        attributeURI:
          type: string
          format: uri
        attributeValue:
          type: string
    LevelOfAssurance:
      type: string
      enum:
        - Low
        - Substantial
        - High
      description: Das Vertrauensniveau gemäß eIDAS oder ähnlichen Standards.
    OotsMediaType:
      type: string
      enum:
        - image/jpeg
        - image/jpg
        - image/png
        - image/svg+xml
        - application/pdf
        - application/json
        - application/xml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
